<!doctype html>

<html>

<head>
    <title>
        &Bobabar
    </title>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width,user-scalable=no,initial-scale=1">
    <meta name="robots" content="NOINDEX,NOFOLLOW">
    <meta name="apple-mobile-web-app-capable" content="yes">

    <!-- START STYLES -->

    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="<?=base_url();?>assets/materialize/dist/css/materialize.min.css">

    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- END STYLES -->

    <!-- START PLUGINS -->

    <!-- jQuery v3.5.1 -->
    <script src="<?=base_url();?>assets/vendor/jquery/jquery-3.5.1.min.js?v3.5.1"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="<?=base_url();?>assets/materialize/dist/js/materialize.min.js"></script>

</head>

<style>

    html {
        background-color: rgb(250, 229, 200);
    }

    nav {
        background-color: #c1dbd0;
        top: 0;
        position: fixed;
        z-index: 1000;
        padding: 0 30px;
        box-shadow: none;
        -webkit-box-shadow: none;
    }

    nav ul a {
        color: #fae5c8;
        font-weight: 750;
    }

    .menu.active a {
        color: rgb(214, 35, 0);
    }

    .img-head {
        height: 2em;
        width: auto;
        z-index: 10000;
        padding: 0.25em 0;
    }
    
    .wrapper {
        margin-top: 64px;
    }
    
    .img-banner {
        width: 100%;
    }

    .home-content, .franchise-content, .flavour-content, .contact-content {
        padding: 5em 10em;
    }

    .card {
        position: initial;
        border: none;
        font-size: inherit;
        text-align: left;
        background: white;
        border-radius: 1em;
        box-shadow: rgb(73 73 73 / 20%) 0px 0px 4px 0px;
        transition: box-shadow 0.3s ease 0s;
    }

    .card .card-content {
        padding: 1em 1.5em;
    }

    .card .card-image.with-content img {
        border-top-left-radius: 1em;
        border-top-right-radius: 1em;
    }

    .card .card-image.image-only img {
        border-radius: 1em;
    }

    .footer {
        display: block;
        position: relative;
        bottom: 0;
        left: 0;
        background-color: rgb(80, 35, 20);
        width: 100%;
        height: 10em;
        padding: 2.5em 7.5em;
    }

    .footer-title {
        color: rgb(245, 235, 220);
        font-size: 30px;
        font-weight: 900;
    }

    .footer-subtitle {
        color: rgb(245, 235, 220);
    }

    .flavour-banner, .contact-banner {
        line-height: 90%;
        text-transform: none;
        width: 100%;
        color: rgb(245, 235, 220);
        padding: 2rem 0px 2.7rem;
        background-color: rgb(214, 35, 0);
        text-align: center;
        font-size: 2rem;
        font-weight: normal;
    }

    input[type=text]:not(.browser-default):focus:not([readonly])+label,
    input[type=email]:not(.browser-default):focus:not([readonly])+label,
    input[type=number]:not(.browser-default):focus:not([readonly])+label,
    textarea.materialize-textarea:focus:not([readonly])+label {
        color: rgb(80, 35, 20);
    }

    input[type=text]:not(.browser-default):focus:not([readonly]),
    input[type=email]:not(.browser-default):focus:not([readonly]),
    input[type=number]:not(.browser-default):focus:not([readonly]),
    textarea.materialize-textarea:focus:not([readonly]) {
        border-bottom: 1px solid rgb(80, 35, 20);
        box-shadow: 0 1px 0 0 rgb(80, 35, 20);
        color: rgb(80, 35, 20);
    }

    .btn {
        border-radius: .5em;
        text-transform: none;
    }

    .btn, .btn:hover {
        background-color: rgb(80, 35, 20);
    }

    .wa-logo {
        height: 5em;
        float: right;
        position: fixed;
        bottom: 1rem;
        right: 7.5em;
        z-index: 1001;
    }

    .roll-in-left {
        -webkit-animation: roll-in-left 0.6s ease-out both;
                animation: roll-in-left 0.6s ease-out both;
    }
    
    /* General Styles */

    .text-center {
        text-align: center;
    }
    .p-0 {
        padding: 0 !important;
    }

    .mb-0 {
        margin-bottom: 0 !important;
    }

    .mb-1 {
        margin-bottom: 1em !important;
    }

    .mb-2 {
        margin-bottom: 2em !important;
    }

    .mb-3 {
        margin-bottom: 3em !important;
    }

    .mb-4 {
        margin-bottom: 4em !important;
    }

    .mb-5 {
        margin-bottom: 5em !important;
    }

    .mt-5 {
        margin-top: 5em !important;
    }

    /* ----------------------------------------------
    * Generated by Animista on 2021-2-24 15:9:33
    * Licensed under FreeBSD License.
    * See http://animista.net/license for more info. 
    * w: http://animista.net, t: @cssanimista
    * ---------------------------------------------- */

    /**
    * ----------------------------------------
    * animation roll-in-left
    * ----------------------------------------
    */
    @-webkit-keyframes roll-in-left {
    0% {
        -webkit-transform: translateX(-800px) rotate(-540deg);
                transform: translateX(-800px) rotate(-540deg);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateX(0) rotate(0deg);
                transform: translateX(0) rotate(0deg);
        opacity: 1;
    }
    }
    @keyframes roll-in-left {
    0% {
        -webkit-transform: translateX(-800px) rotate(-540deg);
                transform: translateX(-800px) rotate(-540deg);
        opacity: 0;
    }
    100% {
        -webkit-transform: translateX(0) rotate(0deg);
                transform: translateX(0) rotate(0deg);
        opacity: 1;
    }
    }

</style>

<body>
